### PR TITLE
Fix pdbpp.Pdb.hidden_frames discrepency with IPython.core.debugger.Pdb.hidden_frames

### PR DESCRIPTION
**Pull request by shwina**
Opening this PR primarily for discussion. As mentioned in #408, pdbpp doesn't work with IPython anymore, because `IPython.core.debugger.Pdb` has a [`hidden_frames`](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.debugger.html#IPython.core.debugger.Pdb.hidden_frames) method that is at odds with the [`pdbpp.Pdb.hidden_frames`](https://github.com/pdbpp/pdbpp/blob/master/src/pdbpp.py#L375) attribute.

Just renaming the attribute in `pdbpp` fixes the problem but that's probably not a very good solution.

Any suggestions here? Thanks!

### CODE REVIEW

**Comment by blueyed** [comment]
I think renaming is ok, but I would prefer `_hidden_frames` then.
Also an (integration) test for this would be good then, but I can look into that myself.
(I imagine having tests that would be run optionally with IPython being installed, and having that installed (optionally?) via a tox factor, which gets used on CI then)

I've used this to reproduce it - is there something simpler?
```
% ipython
Python 3.8.6 (default, Sep 30 2020, 04:00:38)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.0.dev -- An enhanced Interactive Python. Type '?' for help.

In [1]: def foo():
   ...:     raise Exception()
   ...:

In [2]: foo()
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-c19b6d9633cf> in <module>
----> 1 foo()

<ipython-input-1-b10094d32c7e> in foo()
      1 def foo():
----> 2     raise Exception()

Exception:

In [3]: %debug
> <ipython-input-1-b10094d32c7e>(2)foo()
      1 def foo():
----> 2     raise Exception()
      3

ipdb++> up
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-bc99e4ec804d> in <module>
----> 1 get_ipython().run_line_magic('debug', '')

...

~/Vcs/ipython/IPython/core/debugger.py in Pdb.do_up(self, arg)
    723 _newindex = self.curindex
    724 counter = 0
--> 725 hidden_frames = self.hidden_frames(self.stack)
    726 for i in range(self.curindex - 1, -1, -1):
    727     frame = self.stack[i][0]

TypeError: 'list' object is not callable
```

**Comment by shwina** [comment]
> I think renaming is ok, but I would prefer _hidden_frames then.

Thanks! I've gone ahead and replaced it with that.

As for the repro, yes - that looks good. If it's useful, here's a slightly more concise repro:

```
In [1]: %debug raise ValueError()
NOTE: Enter 'c' at the ipdb++>  prompt to continue execution.
> <string>(1)<module>()

ipdb++> u
```

**Review by blueyed — COMMENTED** [review]
Thanks for this already.
I've hijacked this now a bit to debug an issue with codecov, will merge when that is resolved / being investigated by them.

**Comment by shwina** [comment]
Thank you so much!

**Pull request merged**
