### PR TITLE
Improve sticky mode  [ci skip]

### LINKED ISSUE #122: print and log statements in sticky mode
Hi! Consider the following simple file:
```python
import logging

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    handlers=[logging.StreamHandler()],
)

breakpoint()
x = 2
print(x)
y = 3
logger.info(y)
z = x + y
```
If I use `sticky_by_default = True` in my config file then when using `n` to move along lines both print and logger statements are ignored (not actually ignored but since the screen is repainted the message is lost/not shown). Is there a way to avoid using this while on sticky mode?

### PR DESCRIPTION
**Pull request by blueyed**
- clear screen before continuing, so that any `print()` from code shows
  up
- it uses `self.print_stack_entry` for the location in the header, which
  is better than the previous filename+lineno

TODO:

- [ ] This will also display "--Return--" now, which might not really be
      feasible.

Fixes https://github.com/antocuni/pdb/issues/122.

### CODE REVIEW

**Comment by petobens** [comment]
Hi! Thanks for the quick fix! Two minor points: i) can we show the output immediately above the pdb prompt rather than on the very top (header)? and ii) can this be extended to work with logger messages?

**Comment by blueyed** [comment]
> can we show the output immediately above the pdb prompt rather than on the very top (header)

Not easily, except for when capturing output (like with https://github.com/antocuni/pdb/pull/77).  Might be worthwhile to change it like this anyway.  Currently it is limited to us having clear the screen somewhere.

> can this be extended to work with logger messages?

Do those work in normal pdb, but not here?

**Comment by petobens** [comment]
> Do those work in normal pdb, but not here?

yep normal pdb does print logger messages (when using `logging.StreamHandler()`).

**Comment by blueyed** [comment]
Hmm, I wonder why it wouldn't work here then - print and this should behave the same, i.e. this PR only moves around the clearing of the screen.
Have you checked that it does not work with this actually?

**Comment by blueyed** [comment]
I still think that something like #77 would be great to have after all, and we should maybe then focus on getting there instead.
@callmekohei ?  (just seen you force-pushed, and it was from your master branch before actually?!)

**Comment by petobens** [comment]
> Have you checked that it does not work with this actually?

Yes. I'm trying the snippet I post in #122: the print statement is printed but the logger message isn't.

> I still think that something like #77 would be great to have after all, and we should maybe then focus on getting there instead.

I agree. But your PR is pretty useful too (and simpler right?).

**Comment by blueyed** [comment]
> and simpler right?

Well, it only tries to stay as close to pdb as possible.
The diff of #77 is not really that big also, but just e.g. capturing stdout etc appears to open a can of worms I think (but not be that bad after all).

Re: logging:

With the following diff you can see that "CL2" appears after the logging output, which I find unexpected.

```diff
diff --git i/pdb.py w/pdb.py
index b8d6b75..0cbe3b1 100644
--- i/pdb.py
+++ w/pdb.py
@@ -746,7 +746,7 @@ def do_undisplay(self, arg):
     def _print_if_sticky(self, clear):
         if self.sticky:
             if clear:
-                self.stdout.write(CLEARSCREEN)
+                self.stdout.write('CL1')
                 self.print_stack_entry(self.stack[self.curindex])
 
             frame, lineno = self.stack[self.curindex]
@@ -852,7 +852,7 @@ def preloop(self):
     def postcmd(self, stop, line):
         super(Pdb, self).postloop()
         if stop and self.sticky:
-            self.stdout.write(CLEARSCREEN)
+            self.stdout.write('CL2')
         return stop
 
     def _get_position_of_arg(self, arg):
```

```
(Pdb++) 
INFO:__main__:3
CL2[0] > /home/user/Vcs/pdbpp/t-122.py(14)<module>()
```

I would have assumed postcmd to be taken out before any code being executed..

Maybe output buffering is not so bad after all? ;D

**Comment by petobens** [comment]
So @blueyed the idea is to make this as close as possible as #77? (I didn't quite get your last comment)

**Comment by blueyed** [comment]
@petobens 
Yeah, it should probably used the mechanism from #77 (output capturing).

**Comment by blueyed** [comment]
Moved to https://github.com/pdbpp/pdbpp/pull/259 - it did not survive the repo shuffling.

**Pull request closed without merging**
