### PR TITLE
add LICENSE.txt

### PR DESCRIPTION
**Pull request by megies**
In setup.py you mention the license to be "BSD". I propose that a License file should be added, also there's old and new BSD license.. I'm assuming you want the new `BSD-3-Clause`?

### CODE REVIEW

**Comment by antocuni** [comment]
thank you!

**Comment by megies** [comment]
Btw. I stumbled over this when working on conda packaging.. see conda-forge/staged-recipes#3215

**Comment by antocuni** [comment]
cool, let me know if there is anything I can do to help you.
I suppose you need a new release with the update LICENSE.txt?

**Comment by megies** [comment]
> I suppose you need a new release with the update LICENSE.txt?

No, not really. I don't think having it is enforced strictly but it's strongly encouraged. It can be included starting with the next build (if the conda packaging succeeds).

> cool, let me know if there is anything I can do to help you.

I'll ping you from that other conda packaging PR if I run into problems..

**Pull request merged**
