### PR TITLE
fixed virtualenv sys.path shuffling issue

### PR DESCRIPTION
**Pull request by emdej**
This solves #84

### CODE REVIEW

**Comment by blueyed** [comment]
I've only skimmed https://github.com/antocuni/pdb/issues/84, but shouldn't it do something in every case?

**Comment by emdej** [comment]
addpackage from site.py processes two lines of pdbmm_hijack_pdb.pth independently. With the first one (not starting with "import") it can either add a directory to sys.path or not.
```
161                 dir, dircase = makepath(sitedir, line)
162                 if not dircase in known_paths and os.path.exists(dir):
163                     sys.path.append(dir)
164                     known_paths.add(dircase)
```
The idea of the if in the second line is to detect whether it was actually added and proceed accordingly.

**Comment by blueyed** [comment]
I see, thanks for explaining it.
Would be worth adding the extended doc to the commit message when (squash-)merging this then.

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
