### PR TITLE
don't error on bare question mark

### PR DESCRIPTION
**Pull request by davidszotten**
could do with a hand writing the test. would ideally like a multiline regex unless we want to hard-code the docs

### CODE REVIEW

**Comment by blueyed** [comment]
> would ideally like a multiline regex

The test method does not support this yet - I've missed this before.

Here we can use monkeypatching I think (pushed as a fixup).

**Comment by blueyed** [comment]
For reference, without this it would cause a SyntaxError:
```
(Pdb++) ?
*** SyntaxError: unexpected EOF while parsing
Traceback (most recent call last):
  File "t.py", line 20, in <module>
    while True:
  File "t.py", line 20, in <module>
    while True:
  File "/usr/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.7/bdb.py", line 112, in dispatch_line
    self.user_line(frame)
  File "/usr/lib/python3.7/pdb.py", line 261, in user_line
    self.interaction(frame, None)
  File "…/src/pdbpp/pdb.py", line 303, in interaction
    return self._interaction(frame, traceback)
  File "…/src/pdbpp/pdb.py", line 331, in _interaction
    self._cmdloop()
  File "/usr/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/usr/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.7/pdb.py", line 418, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/usr/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "…/src/pdbpp/pdb.py", line 725, in do_inspect
    obj = self._getval(arg)
  File "/usr/lib/python3.7/pdb.py", line 1159, in _getval
    return eval(arg, self.curframe.f_globals, self.curframe_locals)
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by davidszotten** [comment]
thanks! fixed the lint error (and raised #287)

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
