### PR TITLE
Modify test script

### PR DESCRIPTION
**Pull request by callmekohei**
I think that `test_pdb.py` to needs a little bit of modifications.

I'm glad of you to modify `test_pdb.py` directly.

Thank you.

### CODE REVIEW

**Comment by cfbolz** [comment]
Ah, cool, this fixes the errors I've been seeing too (apart from one I don't get?). @antocuni, would you have time to look at this?

**Comment by blueyed** [comment]
Since this appears to be due to a newer pytest the requirements should get adjusted accordingly, i.e. add a minimum version.

Also adding nightly to allowed-failures might be a good idea, or is it easy to fix?

**Comment by blueyed** [comment]
Merged into the fork I plan to maintain, with an additional fix for py37: https://github.com/blueyed/pdbpp/pull/2

**Comment by blueyed** [comment]
Closing in favor of https://github.com/antocuni/pdb/pull/101, where this is included.
Thanks!

**Comment by callmekohei** [comment]
Hi! Very thank you! :-)

**Pull request closed without merging**
