### PR TITLE
Revisit Pygments config

### LINKED ISSUE #95: Allow using Pygments styles directly in .pdbrc.py
Hi, I'd like to use Monokai with pdbpp, but it's proving difficult to do that with the basic config.

This code in pdb.py shows that using bg and colorscheme are hardcoded:

```
    def _init_pygments(self):
        if not self.config.use_pygments:
            return False
        try:
            from pygments.lexers import PythonLexer
            from pygments.formatters import TerminalFormatter, Terminal256Formatter
        except ImportError:
            return False

        if hasattr(self, '_fmt'):
            return True
        if hasattr(self.config, 'formatter'):
            self._fmt = self.config.formatter
        else:
            Formatter = (Terminal256Formatter
                         if self.config.use_terminal256formatter
                            and '256color' in os.environ.get('TERM', '')
                         else TerminalFormatter)
            self._fmt = Formatter(bg=self.config.bg,
                                  colorscheme=self.config.colorscheme)
        self._lexer = PythonLexer()
        return True
```

In .pdbrc, it would be great to be able to set 'style' with a TerminalFormatter256, like this:
```
import pygments.styles
class Config(pdb.DefaultConfig):
    style = pygments.styles.get_style_by_name('monokai')
```

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/antocuni/pdb/issues/95.

### CODE REVIEW

**Comment by twmr** [comment]
I'm looking forward to this being merged and released ;)

**Comment by blueyed** [comment]
@thisch 
Thanks for letting me know.. :) 
Have you tried the branch?

(IIRC the last time I've worked on this I've struggled to trigger the ImportError in tests, but have some stash for this I think)

As for a release: there are many changes on master already, and I am not sure I will release them here yet (see #128).

**Comment by twmr** [comment]
Yes, I've tried that branch and I think it works as expected. In the course of that I've added the files .pdbrc and .pydbrc.py to my dotfiles repo (didn't know that pdbpp can be configured using config files).

I think it makes sense to update the screenshot of the README, because the used colorscheme kind of hurts my eyes ;-)

**Comment by blueyed** [comment]
> I think it makes sense to update the screenshot of the README, because the used colorscheme kind of hurts my eyes ;-)

Yeah :+1: :)

I'd be up to take a PR for it - but would eventually do it myself some time later.
(it should also remove the screenshot from the repo, and only use a link (after uploading it to github.com via e.g. a comment).  Would be nice if it featured sticky mode, and also source code formatting therein, and/or via `source` - so multiple screenshots might make sense even, and also some asciinema recording, featuring tab completion; with regard to this make sure to have pyrepl installed (https://github.com/pdbpp/pyrepl))
FWIW I've started this PR after the latest pygments added styles for solarized.

**Comment by blueyed** [comment]
Moved to https://github.com/pdbpp/pdbpp/pull/2.

**Pull request merged**
